version: '3'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service
    ports:
      - 3000:3000
    networks:
      - internal
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    image: web-client
    ports:
      - 5000:3000
    networks:
      - internal

networks:
  internal:
    driver: bridge
    driver_opts:
       com.docker.network.bridge.name: "brinternal"
