version: '3'

services:
  persistence:
    build:
      context: .
      dockerfile: Dockerfile
    image: persistence
  database:
    image: mongo
    volumes:
      - database_data:/data/db
    logging:
      driver: none

volumes:
  database_data:
