name: Test persistence service

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./persistence-service

    steps:
    - name: Checkout current branch (full)
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: persistence-service/package-lock.json
    - run: npm install
    - run: npm test
